name: Build & test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
