name: Style

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Format
        run: cargo fmt -- --check
      - name: Lint
        run: cargo clippy
